name: Mod Autorelease

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Zip mod
      run: |
        zip -r mod.zip . -x ".git/*" -x ".github/*"

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: mod.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}